# "Matrices"
> De la volute de fumée de cigarette, au vol des oiseaux, tout peut s’exprimer en matrice dans la nature.

- categories: [math, matrices]
- image: images/matrix/matrix.jpg
- comments : true

## Domaine
Les matrices sont des objets mathématiques que l’on regroupe dans l’Algèbre Linéaire. Elles permettent d’exprimer des vecteurs dans des espaces à n dimensions. Un vecteur peut être une position, votre géolocalisation sur la Terre, ou tout simplement une information telle que votre rythme cardiaque ou votre revenu. C’est pour cela que notre monde à 3 dimensions spatiales et extensible peuvant recevoir autant de dimension que nécessaire pour décrire la position d’une position appelé vecteur dans un espace à n dimension.

## Opérateur
Quels sont les opérateurs des matrices :
1. Le produit scalaire : équivalent d’une projection d’un premier vecteur, sur le second.
2. Le produit vectoriel : c’est la recherche du vecteur perpendiculaire à un plan formé par deux vecteurs, dont la norme est aussi l’aire de ce plan.
3. La norme : la racine de la somme des carrés des longueurs d’un vecteur sur chaque direction de l’espace à n dimension.
4. Le déterminant : c’est une caractéristique quantitative des normes de vecteurs dans un espace à n dimensions. Si n vaut 2 ou 3, c’est l’aire ou le volume.
5. Le vecteur unitaire : c’est un vecteur colinéaire et de même direction qu’un autre, mais sa norme vaut 1.
6. Le valeur propre : coefficient d’étirement d’un vecteur propre, d’une application linéaire dans un espace vectoriel.
7. La vecteur propre : vecteur qui est juste étiré ou raccourci lors d’une transformation linéaire dans un espace vectoriel.

## Utilisation de Python pour chaque opérateur
Pour réaliser nos calculs nous aurons besoin de la bibliothèque numpy afin de construire nos tableaux de valeurs. Pour l’installation dans Jupyter-notebook, nous pouvons utiliser la commande suivante :

In [ ]:
!pip install scipy numpy sympy

### Chargement des bibliothèques

In [2]:
import numpy as np
from numpy import linalg as LA
from numpy.linalg import eig
from sympy import *

### Produit scalaire

In [2]:
## Algèbre Linéaire
### Produit scalaire: produit de deux vecteurs
f = np.array([1,2,4,6,7])
g = np.array([4,5,3,8,3])
### 1*4+2*5+4*3+6*8+7*3
np.dot(f, g)

95

Dans l’étude du produit vectoriel et de la norme ci-dessous, nous considérons semblables les représentations géométriques et algébriques de vecteurs. Cela nous permet de dire que la norme d’un vecteur h par le produit vectoriel de deux vecteurs f, g est égale à l’aire du plan formé par ces deux derniers vecteurs.

### Produit vectoriel

In [3]:
## Algèbre Linéaire
### Produit vectoriel équivaut au produit extérieur: f x g = f ∧ g 
f = np.array([3,5,2])
g = np.array([5,7,4])
### i(5*4-7*2)+j(5*2-3*4)+k(3*7-5*5)
np.cross(f, g)

array([ 6, -2, -4])

### Norme

In [4]:
## Algèbre Linéaire
### Produit vectoriel équivaut au produit extérieur: f x g = f ∧ g soit le vecteur h
f = np.array([3,5,2])
g = np.array([5,7,4])
### i(5*4-7*2)+j(5*2-3*4)+k(3*7-5*5)
h = np.cross(f, g)
### La norme de h vaut le produit extérieur f ∧ g
LA.norm(h,1)

12.0

### Le déterminant

In [5]:
## Le determinant d’une matrice carré par 2, [[a, b], [c, d]] est ad - bc:
a = np.array(([1,2],[-3,4]))
int(np.linalg.det(a))

10

Nous pouvons tout à fait utiliser plutôt le module sympy et faire le calcul comme suivant.

In [6]:
M = Matrix([[1,2],[-3,4]])
M

Matrix([
[ 1, 2],
[-3, 4]])

In [7]:
M.det()

10

### Le vecteur unitaire

Le vecteur unitaire a une magnitude de 1, sa formule est $\hat{v} = \frac{1}{\lvert\lvert v \rvert\rvert}\cdot v$ .

In [8]:
v = np.arange(3)
v_hat = v / np.linalg.norm(v)
v_hat

array([0.        , 0.4472136 , 0.89442719])

### La valeur propre et le vecteur propre

Dans une application linéaire, un vecteur propre est la transformation linéaire telle celle de la multiplication d’un vecteur par une valeur propre (scalaire).

$T(v)=\lambda v$

En somme, pour une transformation donnée, c’est les vecteurs qui sont sur la ou les ligne(s) de transformation(s) et pour qui tout vecteur se trouvant dessus sera soit étiré soit réduit mais dont la direction ne changera pas.

In [9]:
a = np.array([[2, 0, 0], [0, 3, 4], [0, 4, 9]])
values , vectors = eig(a)
print(values)
print(vectors)

[11.  1.  2.]
[[ 0.          0.          1.        ]
 [ 0.4472136   0.89442719  0.        ]
 [ 0.89442719 -0.4472136   0.        ]]


De même, avec le module python sympy, nous pouvons déclarer une matrice M et exécuter les calculs.

In [10]:
M = Matrix([[2, 0, 0], [0, 3, 4], [0, 4, 9]])
M

Matrix([
[2, 0, 0],
[0, 3, 4],
[0, 4, 9]])

In [11]:
M.eigenvals()

{11: 1, 2: 1, 1: 1}

In [12]:
M.eigenvects()

[(1,
  1,
  [Matrix([
   [ 0],
   [-2],
   [ 1]])]),
 (2,
  1,
  [Matrix([
   [1],
   [0],
   [0]])]),
 (11,
  1,
  [Matrix([
   [  0],
   [1/2],
   [  1]])])]

In [3]:
M = Matrix([[2, 4], [3, 13]])
M

Matrix([
[2,  4],
[3, 13]])

In [4]:
M.eigenvals()

{14: 1, 1: 1}